### ISSUE TITLE
Library not loaded: @rpath/CorePaymentCard.framework/CorePaymentCard 

### ISSUE THREAD

**Issue by ajayPris** [square/reader-sdk-ios-sample-apps#1]
i couldn't able to run a build in real device and as well as not able to upload a build. i also followed all steps of READER SDK (Build on iOS). Please help to resolve this bug.

SquareReaderSDK.xcframework Version is : 1.4.7
My Xcode version is :12.3 

![hey_taxi_error](https://user-images.githubusercontent.com/24670996/107037427-11de0e80-67e1-11eb-998b-2fab4affa94e.png)
![Screen Shot 2021-02-05 at 7 06 24 PM](https://user-images.githubusercontent.com/24670996/107040820-bf532100-67e5-11eb-8830-3bd4c9c231f7.png)

**Comment by MikeSilvis** [comment]
@ajayPris i'm able to successfully deploy on xcode 12.3 to a device. 

- When embedding the framework ensure that you have "Embed & Sign" enabled.
- Further under build phases be sure to have the setup script AFTER the embed phase
